### ISSUE TITLE
Error: InvalidInput

### ISSUE THREAD

**Issue by git-hobit** [yoshuawuyts/miow#59]
Hello!

I wanted to experiment with termination ports and this library seems to offer the most convenient api for this.
It seems that I'm doing something wrong, but maybe the error does take place.

In any case, I really hope for some kind of hint.

So, my goal is to read the file, but I get an error when trying to add a handle to the port.

**Code:**
```
fn main() -> Result<()> {
    let port = CompletionPort::new(16)?;
    let file = File::open("input.txt")?;
    port.add_handle(0, &file)?;
    Ok(())
}
```

**Error:**
`
Error: Os { code: 87, kind: InvalidInput, message: "The parameter is set incorrectly." }
`

UPD:
It seems to be related to the specific features of the system.
I will mark it as closed, but if I find a solution, I will definitely let you know.

**Comment by git-hobit** [comment]
It's still not related to the system.

At the moment there are two versions of the origin of the error:
1. Something is wrong with my code (more likely)
2. Error in miow

**Comment by rs0d** [comment]
Have you solved it now?

**Comment by tokcum** [comment]
Hi,

I've the same issue. I cloned miow's repository and run `cargo test`. This is what I get.

```
failures:

thread '<unnamed>' panicked at src\pipe.rs:745:25:
File::create(name) failed with Os { code: 87, kind: InvalidInput, message: "Falscher Parameter." }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'pipe::tests::named_read_overlapped' panicked at src\pipe.rs:756:13:
a.read_overlapped(&mut b, over.raw()) failed with Os { code: 109, kind: BrokenPipe, message: "Die Pipe wurde beendet." }


failures:
    pipe::tests::named_read_overlapped

test result: FAILED. 24 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.02s

error: test failed, to rerun pass `--lib`
```
